#!/bin/bash

# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

site_dir="${OPENSHIFT_DATA_DIR}site/"
config_dir="${site_dir}etc/"

# prepopulate site dir with ssh keys
if [ ! -d "${site_dir}" ]
then
	java -jar ${OPENSHIFT_DATA_DIR}gerrit.war init --batch --no-auto-start --install-plugin download-commands --install-plugin commit-message-length-validator -d ${site_dir}

	cat >${config_dir}gerrit.config <<EOF
[gerrit]
	basePath = git
	canonicalWebUrl = https://${OPENSHIFT_APP_DNS}/
[database]
	type = h2
	database = ${OPENSHIFT_DATA_DIR}site/db/ReviewDB
[index]
	type = LUCENE
[auth]
	type = OPENID
[receive]
	enableSignedPush = false
[sendemail]
	smtpServer = localhost
[container]
	user = ${OPENSHIFT_GEAR_UUID}
	heapLimit = ${OPENSHIFT_GEAR_MEMORY_MB}m
	packedGitLimit = $((${OPENSHIFT_GEAR_MEMORY_MB}/4))m
[sshd]
	listenAddress = off
[httpd]
	listenUrl = proxy-https://${OPENSHIFT_DIY_IP}:${OPENSHIFT_DIY_PORT}/
[cache]
	directory = cache
EOF

fi

#Delete gerrit.war
if [ -f "${install_file}" ]
then
	rm ${OPENSHIFT_DATA_DIR}gerrit.war
fi
